require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('./models/User');

const bartenders = [
  {
    email: 'marcus.rivera@demo.com',
    profile: {
      name: 'Marcus Rivera',
      avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
      photos: ['https://randomuser.me/api/portraits/men/32.jpg'],
      title: 'Craft Cocktail Specialist',
      yearsExp: 8,
      specialties: ['Craft Cocktails', 'Flair Bartending', 'Spirits Expert'],
      certs: ['TIPS Certified', 'Cicerone'],
      venueTypesLove: ['Upscale Bar', 'Rooftop', 'Hotel Bar'],
      availability: { sun: false, mon: true, tue: true, wed: true, thu: true, fri: true, sat: true },
      availableNow: true,
      bio: 'Passionate about the art of mixology with 8 years crafting cocktails at NYC\'s top venues. Flair certified and obsessed with craft spirits.',
      hourlyRate: { min: 32, max: 40 },
    },
    location: { city: 'New York', neighborhood: 'Lower East Side', lat: 40.7155, lng: -73.9841 },
  },
  {
    email: 'sofia.chen@demo.com',
    profile: {
      name: 'Sofia Chen',
      avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
      photos: ['https://randomuser.me/api/portraits/women/44.jpg'],
      title: 'Wine & Cocktail Expert',
      yearsExp: 6,
      specialties: ['Wine Expert', 'Craft Cocktails', 'Sake'],
      certs: ['Sommelier', 'TIPS Certified'],
      venueTypesLove: ['Restaurant', 'Hotel Bar', 'Upscale Bar'],
      availability: { sun: true, mon: false, tue: false, wed: true, thu: true, fri: true, sat: true },
      availableNow: false,
      bio: 'Certified sommelier turned cocktail innovator. I bring elegance and precision to every pour. Former lead bartender at Michelin-starred venues.',
      hourlyRate: { min: 30, max: 38 },
    },
    location: { city: 'New York', neighborhood: 'Midtown', lat: 40.7549, lng: -73.9840 },
  },
  {
    email: 'james.okafor@demo.com',
    profile: {
      name: 'James Okafor',
      avatar: 'https://randomuser.me/api/portraits/men/75.jpg',
      photos: ['https://randomuser.me/api/portraits/men/75.jpg'],
      title: 'High Volume Bar Pro',
      yearsExp: 10,
      specialties: ['Shot Specialist', 'Draft Beer', 'High Volume'],
      certs: ['TIPS Certified', 'ServSafe'],
      venueTypesLove: ['Nightclub', 'Sports Bar', 'Event Venue'],
      availability: { sun: false, mon: false, tue: false, wed: false, thu: true, fri: true, sat: true },
      availableNow: true,
      bio: '10 years behind the stick at NYC\'s busiest nightclubs. I thrive under pressure and can handle 500+ covers without breaking a sweat.',
      hourlyRate: { min: 28, max: 35 },
    },
    location: { city: 'New York', neighborhood: 'Chelsea', lat: 40.7465, lng: -74.0014 },
  },
  {
    email: 'elena.vasquez@demo.com',
    profile: {
      name: 'Elena Vasquez',
      avatar: 'https://randomuser.me/api/portraits/women/28.jpg',
      photos: ['https://randomuser.me/api/portraits/women/28.jpg'],
      title: 'Mixologist & Brand Ambassador',
      yearsExp: 5,
      specialties: ['Craft Cocktails', 'Spirits Expert', 'Flair Bartending'],
      certs: ['TIPS Certified'],
      venueTypesLove: ['Rooftop', 'Upscale Bar', 'Event Venue'],
      availability: { sun: true, mon: true, tue: true, wed: true, thu: true, fri: true, sat: true },
      availableNow: true,
      bio: 'Brand ambassador for three premium spirits brands. I bring creativity and presentation to every shift — your guests will talk about my drinks.',
      hourlyRate: { min: 30, max: 42 },
    },
    location: { city: 'New York', neighborhood: 'Williamsburg', lat: 40.7081, lng: -73.9571 },
  },
  {
    email: 'tyler.brooks@demo.com',
    profile: {
      name: 'Tyler Brooks',
      avatar: 'https://randomuser.me/api/portraits/men/52.jpg',
      photos: ['https://randomuser.me/api/portraits/men/52.jpg'],
      title: 'Beer & Whiskey Specialist',
      yearsExp: 4,
      specialties: ['Draft Beer', 'Beer & Wine', 'Spirits Expert'],
      certs: ['Cicerone', 'ServSafe'],
      venueTypesLove: ['Brewery', 'Sports Bar', 'Restaurant'],
      availability: { sun: true, mon: true, tue: false, wed: false, thu: true, fri: true, sat: true },
      availableNow: false,
      bio: 'Cicerone-certified beer specialist with deep knowledge of craft brews and whiskey. Perfect for taprooms, gastropubs, and sports bars.',
      hourlyRate: { min: 25, max: 32 },
    },
    location: { city: 'New York', neighborhood: 'Astoria', lat: 40.7721, lng: -73.9302 },
  },
  {
    email: 'priya.sharma@demo.com',
    profile: {
      name: 'Priya Sharma',
      avatar: 'https://randomuser.me/api/portraits/women/61.jpg',
      photos: ['https://randomuser.me/api/portraits/women/61.jpg'],
      title: 'Luxury Bar Curator',
      yearsExp: 9,
      specialties: ['Craft Cocktails', 'Wine Expert', 'Spirits Expert'],
      certs: ['Sommelier', 'TIPS Certified', 'ServSafe'],
      venueTypesLove: ['Hotel Bar', 'Upscale Bar', 'Rooftop'],
      availability: { sun: false, mon: true, tue: true, wed: true, thu: true, fri: false, sat: false },
      availableNow: false,
      bio: 'Nine years curating cocktail programs at 5-star hotels. Expert in aged spirits, Japanese whisky, and bespoke tasting menus.',
      hourlyRate: { min: 38, max: 50 },
    },
    location: { city: 'New York', neighborhood: 'Upper East Side', lat: 40.7736, lng: -73.9566 },
  },
  {
    email: 'carlos.mendez@demo.com',
    profile: {
      name: 'Carlos Mendez',
      avatar: 'https://randomuser.me/api/portraits/men/41.jpg',
      photos: ['https://randomuser.me/api/portraits/men/41.jpg'],
      title: 'Latin Spirits & Cocktail Pro',
      yearsExp: 7,
      specialties: ['Craft Cocktails', 'Flair Bartending', 'Shot Specialist'],
      certs: ['TIPS Certified'],
      venueTypesLove: ['Nightclub', 'Rooftop', 'Sports Bar'],
      availability: { sun: false, mon: false, tue: false, wed: true, thu: true, fri: true, sat: true },
      availableNow: true,
      bio: 'Specializing in Latin-inspired cocktails and mezcal. High energy behind the bar with flair skills that keep guests entertained all night.',
      hourlyRate: { min: 28, max: 36 },
    },
    location: { city: 'New York', neighborhood: 'East Harlem', lat: 40.7957, lng: -73.9389 },
  },
  {
    email: 'jessica.park@demo.com',
    profile: {
      name: 'Jessica Park',
      avatar: 'https://randomuser.me/api/portraits/women/17.jpg',
      photos: ['https://randomuser.me/api/portraits/women/17.jpg'],
      title: 'Cocktail Artist & Educator',
      yearsExp: 6,
      specialties: ['Craft Cocktails', 'Wine Expert', 'Beer & Wine'],
      certs: ['TIPS Certified', 'ServSafe', 'Cicerone'],
      venueTypesLove: ['Restaurant', 'Hotel Bar', 'Event Venue'],
      availability: { sun: true, mon: true, tue: true, wed: false, thu: false, fri: true, sat: true },
      availableNow: false,
      bio: 'Cocktail educator who runs workshops by day and crafts elevated drinks by night. Triple certified and always learning.',
      hourlyRate: { min: 30, max: 38 },
    },
    location: { city: 'New York', neighborhood: 'Park Slope', lat: 40.6710, lng: -73.9814 },
  },
  {
    email: 'damien.cole@demo.com',
    profile: {
      name: 'Damien Cole',
      avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
      photos: ['https://randomuser.me/api/portraits/men/22.jpg'],
      title: 'Nightlife Veteran',
      yearsExp: 12,
      specialties: ['Shot Specialist', 'High Volume', 'Flair Bartending'],
      certs: ['TIPS Certified', 'ServSafe'],
      venueTypesLove: ['Nightclub', 'Sports Bar', 'Rooftop'],
      availability: { sun: false, mon: false, tue: false, wed: false, thu: true, fri: true, sat: true },
      availableNow: true,
      bio: '12 years in NYC nightlife — I\'ve seen it all. Unmatched speed, consistency, and crowd control. The go-to for your busiest nights.',
      hourlyRate: { min: 30, max: 40 },
    },
    location: { city: 'New York', neighborhood: 'Meatpacking District', lat: 40.7408, lng: -74.0074 },
  },
  {
    email: 'ava.thornton@demo.com',
    profile: {
      name: 'Ava Thornton',
      avatar: 'https://randomuser.me/api/portraits/women/83.jpg',
      photos: ['https://randomuser.me/api/portraits/women/83.jpg'],
      title: 'Farm-to-Glass Mixologist',
      yearsExp: 5,
      specialties: ['Craft Cocktails', 'Beer & Wine', 'Wine Expert'],
      certs: ['TIPS Certified'],
      venueTypesLove: ['Restaurant', 'Brewery', 'Upscale Bar'],
      availability: { sun: true, mon: false, tue: true, wed: true, thu: true, fri: true, sat: false },
      availableNow: false,
      bio: 'Seasonal, locally-sourced cocktail programs are my passion. I work closely with chefs to create drinks that complement the food menu.',
      hourlyRate: { min: 28, max: 36 },
    },
    location: { city: 'New York', neighborhood: 'Brooklyn Heights', lat: 40.6958, lng: -73.9936 },
  },
];

const venues = [
  {
    email: 'rooftopbar.nyc@demo.com',
    profile: {
      venueName: 'The Rooftop Bar NYC',
      venueType: 'Upscale Rooftop & Lounge',
      avatar: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80'],
      address: '230 5th Ave, New York, NY 10001',
      rating: 4.8,
      seats: 200,
      priceRange: '$$$',
      openShifts: 3,
      activelyHiring: true,
      lookingFor: ['Craft Cocktails', 'Flair Bartending', 'Spirits Expert'],
      vibe: ['Upscale', 'Rooftop', 'Live DJs', 'Weekend Nights'],
      perks: '$30–$38/hr + pooled tips',
      bio: 'NYC\'s premier rooftop destination with panoramic Manhattan views. We host 500+ guests on weekends and need top-tier talent to match our vibe.',
    },
    location: { city: 'New York', neighborhood: 'Flatiron', lat: 40.7448, lng: -73.9884 },
  },
  {
    email: 'barleyco@demo.com',
    profile: {
      venueName: 'Barley & Co.',
      venueType: 'Craft Beer & Cocktail Bar',
      avatar: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=600&q=80'],
      address: '87 Bedford Ave, Brooklyn, NY 11211',
      rating: 4.6,
      seats: 80,
      priceRange: '$$',
      openShifts: 2,
      activelyHiring: true,
      lookingFor: ['Craft Cocktails', 'Beer & Wine', 'Draft Beer'],
      vibe: ['Craft Beer', 'Chill', 'Weekend Nights'],
      perks: '$25–$30/hr + tips',
      bio: 'Beloved Williamsburg neighborhood bar with 24 craft taps and a rotating seasonal cocktail menu. Community-focused and fast-paced on weekends.',
    },
    location: { city: 'New York', neighborhood: 'Williamsburg', lat: 40.7143, lng: -73.9614 },
  },
  {
    email: 'vinobistro@demo.com',
    profile: {
      venueName: 'Vino Bistro',
      venueType: 'Wine Bar & Restaurant',
      avatar: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&q=80'],
      address: '15 E 48th St, New York, NY 10017',
      rating: 4.7,
      seats: 60,
      priceRange: '$$$',
      openShifts: 1,
      activelyHiring: true,
      lookingFor: ['Wine Expert', 'Craft Cocktails', 'Sommelier'],
      vibe: ['Upscale', 'Chill'],
      perks: '$35–$45/hr + tips',
      bio: 'An intimate Midtown wine bar and bistro with a curated list of 200+ wines. We value deep wine knowledge and exceptional hospitality.',
    },
    location: { city: 'New York', neighborhood: 'Midtown East', lat: 40.7568, lng: -73.9766 },
  },
  {
    email: 'clubnoir@demo.com',
    profile: {
      venueName: 'Club Noir',
      venueType: 'Upscale Nightclub',
      avatar: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=600&q=80'],
      address: '512 W 27th St, New York, NY 10001',
      rating: 4.5,
      seats: 400,
      priceRange: '$$$$',
      openShifts: 4,
      activelyHiring: true,
      lookingFor: ['Shot Specialist', 'High Volume', 'Flair Bartending'],
      vibe: ['Upscale', 'Live DJs', 'High Volume', 'Weekend Nights'],
      perks: '$28–$35/hr + pooled tips + bottle service commission',
      bio: 'Chelsea\'s most exclusive nightclub. We move 1,000+ guests Thu–Sat and need speed demons who can keep lines short and energy high.',
    },
    location: { city: 'New York', neighborhood: 'Chelsea', lat: 40.7491, lng: -74.0027 },
  },
  {
    email: 'sportszone@demo.com',
    profile: {
      venueName: 'The Sports Zone',
      venueType: 'Sports Bar',
      avatar: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&q=80'],
      address: '340 W 42nd St, New York, NY 10036',
      rating: 4.3,
      seats: 150,
      priceRange: '$$',
      openShifts: 3,
      activelyHiring: true,
      lookingFor: ['Draft Beer', 'Shot Specialist', 'High Volume'],
      vibe: ['Sports', 'High Volume', 'Chill'],
      perks: '$22–$28/hr + tips',
      bio: 'Times Square\'s ultimate sports bar with 40+ screens. Game days are non-stop — we need bartenders who love the energy and can pour fast.',
    },
    location: { city: 'New York', neighborhood: 'Hell\'s Kitchen', lat: 40.7580, lng: -74.0028 },
  },
  {
    email: 'grandhotelbar@demo.com',
    profile: {
      venueName: 'The Grand Hotel Bar',
      venueType: '5-Star Hotel Bar',
      avatar: 'https://images.unsplash.com/photo-1561047029-3000c68339ca?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1561047029-3000c68339ca?w=600&q=80'],
      address: '768 5th Ave, New York, NY 10019',
      rating: 4.9,
      seats: 50,
      priceRange: '$$$$',
      openShifts: 2,
      activelyHiring: true,
      lookingFor: ['Craft Cocktails', 'Wine Expert', 'Spirits Expert'],
      vibe: ['Upscale', 'Chill'],
      perks: '$42–$55/hr + gratuity',
      bio: 'The lobby bar at one of NYC\'s most storied 5-star hotels. Impeccable standards, discerning guests, and unmatched compensation.',
    },
    location: { city: 'New York', neighborhood: 'Midtown', lat: 40.7638, lng: -73.9730 },
  },
  {
    email: 'eastvillagebrewery@demo.com',
    profile: {
      venueName: 'East Village Brewing Co.',
      venueType: 'Craft Brewery & Taproom',
      avatar: 'https://images.unsplash.com/photo-1559818488-e078c3c89c73?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1559818488-e078c3c89c73?w=600&q=80'],
      address: '205 E 7th St, New York, NY 10009',
      rating: 4.6,
      seats: 100,
      priceRange: '$$',
      openShifts: 2,
      activelyHiring: true,
      lookingFor: ['Draft Beer', 'Beer & Wine', 'Cicerone'],
      vibe: ['Craft Beer', 'Chill'],
      perks: '$24–$30/hr + tips + staff beer allowance',
      bio: 'Award-winning East Village microbrewery with 20 house taps. Beer geeks welcome — we want people who can guide guests through our rotating selection.',
    },
    location: { city: 'New York', neighborhood: 'East Village', lat: 40.7265, lng: -73.9815 },
  },
  {
    email: 'azulrooftop@demo.com',
    profile: {
      venueName: 'Azul Rooftop Lounge',
      venueType: 'Rooftop Bar & Event Space',
      avatar: 'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=600&q=80'],
      address: '1 Hotel Brooklyn Bridge, Brooklyn, NY 11201',
      rating: 4.7,
      seats: 175,
      priceRange: '$$$',
      openShifts: 3,
      activelyHiring: true,
      lookingFor: ['Craft Cocktails', 'Flair Bartending', 'Spirits Expert'],
      vibe: ['Rooftop', 'Upscale', 'Live DJs', 'Weekend Nights'],
      perks: '$30–$40/hr + tips + event bonuses',
      bio: 'Brooklyn\'s hottest rooftop with stunning Manhattan views. Summer season is in full swing — we need charismatic bartenders who can perform under the spotlight.',
    },
    location: { city: 'New York', neighborhood: 'DUMBO', lat: 40.7032, lng: -73.9931 },
  },
  {
    email: 'harlemsupper@demo.com',
    profile: {
      venueName: 'Harlem Supper Club',
      venueType: 'Jazz Supper Club & Bar',
      avatar: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80'],
      address: '2150 Adam Clayton Powell Jr Blvd, New York, NY 10027',
      rating: 4.8,
      seats: 120,
      priceRange: '$$$',
      openShifts: 2,
      activelyHiring: true,
      lookingFor: ['Craft Cocktails', 'Wine Expert', 'Spirits Expert'],
      vibe: ['Upscale', 'Chill', 'Live DJs'],
      perks: '$32–$42/hr + tips',
      bio: 'Legendary Harlem supper club with live jazz nightly. We\'re known for our classic cocktail program and warm hospitality. Looking for passionate storytellers.',
    },
    location: { city: 'New York', neighborhood: 'Harlem', lat: 40.8090, lng: -73.9499 },
  },
  {
    email: 'fidilounge@demo.com',
    profile: {
      venueName: 'FiDi Lounge & Bar',
      venueType: 'After-Work Bar & Lounge',
      avatar: 'https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=600&q=80',
      photos: ['https://images.unsplash.com/photo-1537047902294-62a40c20a6ae?w=600&q=80'],
      address: '85 Broad St, New York, NY 10004',
      rating: 4.4,
      seats: 90,
      priceRange: '$$',
      openShifts: 2,
      activelyHiring: true,
      lookingFor: ['Craft Cocktails', 'Beer & Wine', 'Draft Beer'],
      vibe: ['Chill', 'Upscale'],
      perks: '$26–$34/hr + tips',
      bio: 'Financial District\'s go-to after-work spot for Wall Street professionals. Mon–Fri happy hour is our bread and butter — consistent, fast, and personable bartenders needed.',
    },
    location: { city: 'New York', neighborhood: 'Financial District', lat: 40.7044, lng: -74.0087 },
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  // Clear existing demo users
  await User.deleteMany({ email: /demo\.com$/ });
  console.log('Cleared existing demo users');

  const password = await bcrypt.hash('Demo1234!', 12);

  // Seed bartenders
  for (const b of bartenders) {
    await User.create({
      email: b.email,
      password,
      role: 'bartender',
      profile: b.profile,
      location: b.location,
      isOnboarded: true,
      rating: +(3.8 + Math.random() * 1.2).toFixed(1),
      reviewCount: Math.floor(10 + Math.random() * 80),
    });
    console.log(`Created bartender: ${b.profile.name}`);
  }

  // Seed venues
  for (const v of venues) {
    await User.create({
      email: v.email,
      password,
      role: 'venue',
      profile: v.profile,
      location: v.location,
      isOnboarded: true,
      rating: +(4.0 + Math.random() * 0.9).toFixed(1),
      reviewCount: Math.floor(20 + Math.random() * 200),
    });
    console.log(`Created venue: ${v.profile.venueName}`);
  }

  console.log('\n✓ Seed complete — 10 bartenders + 10 venues created');
  console.log('All demo accounts use password: Demo1234!');
  process.exit(0);
}

seed().catch(err => {
  console.error('Seed error:', err);
  process.exit(1);
});
